name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install yapf
        shell: bash

      - name: Format code with yapf
        run: |
          set -e
          if ! python --version 2>&1; then
            yapf -r ntfy -d
            [ "$(yapf -r ntfy -d | wc -l)" -eq 0 ]
          fi
        shell: bash
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "pypy-3.10"]
        exclude:
          - os: macos-latest
            python-version: pypy-3.10
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          set -e
          python -m pip install --upgrade pip setuptools
          pip install .
          pip install -r test-requirements.txt
          pip install twine pytest-cov
        shell: bash

      - name: Run tests
        run: |
          set -e
          pytest --cov=ntfy --ignore 'tests/test_xmpp.py' -k 'not test_xmpp' tests 
        shell: bash

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Signal test completion to coverage
      uses: coverallsapp/github-action@v2
      with:
        parallel-finished: true